### PR TITLE
First Take on Object Modeler

### PR DESCRIPTION
**Pull request by aaronbenz**
- Essentially created dynamic logic around the response object so that we can actually handle a data object as opposed to a JSON with response header info. (certainly some more to do, but this is a start for the response object from the uber api). Check out obj_model.py in examples to get an idea of what you can do (could make the .md example alot prettier now...)

- The response_obj that is being passed is really temporary for a better solution... As in there really should be a request object for pre-validation purposes and object handling prior to sending the request off to Uber api. Also, this handling allowed for none of your tests or current functionality to be affected

- The metaclass around the uber objects isn't really necessary, but would allow you to look up a class by an endpoint as well as keeps the objects orderly (as in making sure there is only 1 object per endpoint).

- The 'serialize' function in every data object can be used for any jsonify methods for easier api development

- Overall, wanted to get something out there to see where you guys wanted to go with it

### CODE REVIEW

**Comment by aaronbenz** [comment]
Also, definetley better in another branch for now, but I don't think I was allowed to make a pull request on a branch that doesn't exist in your dir yet

**Comment by Lee-Kevin** [comment]
Why can't be used in china

**Comment by christinekim** [comment]
Thanks Aaron - we're going to look into this and get back to you soon!

**Comment by christinekim** [comment]
Hi Aaron - right now, mapping responses to object is not something we are going to do just yet. We are going to stick with a thin wrapper that just returns the JSON response in a Python dictionary. If anything changes, I'll reach out - thanks again for using the SDK!

**Pull request closed without merging**
