### PR TITLE
Added Python 3 support (while continuing Python 2 compatibility)

### PR DESCRIPTION
**Pull request by merrywhether**
Updated library to Python 3 whilst preserving Python 2 compatibility.

Leveraged try/except blocks for imports instead of using a compatibility library to keep footprint small. Several of the tests relied on Python 2's dict key order-preservation-as-a-side-effect, but this broke in Python 3, so I updated the relevant methods to use an OrderedDict instead of the default orderless dict. As Python 3 no longer had this order-by-luck functionality, I updated the vcr cassettes to put latitude before longitude and start before end, since the tests were expecting a specific ordering of the query parameters (even though this wouldn't be important in real-world functionality). All tests pass (repeatedly) in both Python 2.7 and Python 3.5 now.

Addresses issues #4, #5, & #6.

### CODE REVIEW

**Comment by merrywhether** [comment]
I've agreed to the Uber CLA as well.

**Comment by robbiet480** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: thanks @merrywhether!!!

**Comment by christinekim** [comment]
Fantastic, I also just tested in Python 2 and 3. Thanks @merrywhether - OrderedDict usage looks good to me, too.

**Comment by robbiet480** [comment]
@christinekim Thanks for merging! Can a release go out on Pip soon?

**Comment by christinekim** [comment]
Yes @robbiet480 I can get that done today. Will update here when it is complete :)

**Comment by robbiet480** [comment]
Thanks @christinekim!

**Comment by christinekim** [comment]
Hi all - the newest distribution is up on the Python Package Index: https://pypi.python.org/pypi/uber_rides/0.2.1

**Comment by merrywhether** [comment]
Cool, thanks!

**Comment by christinekim** [comment]
:+1:

**Pull request merged**
