### PR TITLE
Fix links in the README.rst

### PR DESCRIPTION
**Pull request by Perados**
The syntax for two links was wrong for the rst format.

### CODE REVIEW

**Comment by Perados** [comment]
Woah... Thank you... 👎

**Comment by dustinwhittle** [comment]
I wasn't able to merge your pr since you didn't sign the cla. I appreciate your report and feedback and have made improvements to the readme that should resolve your feedback.

**Comment by Perados** [comment]
I did sign the CLA. I don't know why it says I did not...

screenshot 2017-01-24 23 32 43

**Comment by dustinwhittle** [comment]
My apologies - not sure what happened. I will investigate -- We definitely want to encourage contributions and have a very lightweight process. I appreciate your help!

**Comment by arogal** [comment]
Hi @Perados. Apologize for the issues here. If you undelete the patch-1 branch, we can reopen the PR and attempt to fix things. I definitely see that you have signed the CLA. Thanks!

**Comment by Subzidion** [comment]
Dustin already committed the changes on his own, so.

**Comment by arogal** [comment]
@Subzidion gotcha. In either case, happy to make sure our CLA process is working for everyone rather than against going forward. If you see a case where things aren't working (I've already commented on https://github.com/uber/vertica-python/issues/139), happy to investigate again if you mention me. Thanks.

**Pull request closed without merging**
