### PR TITLE
Add seat_count support to get_price_estimates

### PR DESCRIPTION
**Pull request by robbiet480**

### CODE REVIEW

**Comment by christinekim** [comment]
Thanks for your contribution @robbiet480 - can you make the default `seat_count=None` instead of `seat_count=2` as you have now?

When we document that the default is 2, we mean that the Uber API will assume 2 if no `seat_count` parameter is sent, so there is no need to set a default at the SDK level.

**Comment by christinekim** [comment]
Also please sign our cla (t.uber.com/cla) so we can accept your PR when it's ready!

**Comment by robbiet480** [comment]
@christinekim `seat_count=None` now and the CLA has been signed!

**Comment by christinekim** [comment]
Thanks, your PR has been merged and I'm distributing the new version on PyPi now

**Pull request merged**
