### PR TITLE
Make adjustments in order to support Python 3.5

### PR DESCRIPTION
**Pull request by denismakogon**
Make adjustments in order to support Python 3.5
Issue addressed -   #4  #5 #6

### CODE REVIEW

**Comment by denismakogon** [comment]
@christinekim Would you mind reviewing code and releasing a new version that support Py3.5 - is urgent to my project to have uber support within its python SDK

**Comment by denismakogon** [comment]
@shampab hey, could you please review, merge, and release new version of Uber SDK it is needed for my project ASAP.

**Comment by merrywhether** [comment]
+1

**Comment by christinekim** [comment]
Hi @denismakogon most changes look good to me. However in Python 2, `raw_input()` returns a string, and `input()` tries to run the input as a Python expression. Though you are trying to use this kit for Python 3, I don't want to introduce this behavior for Python 2 users.

Could you please bind `raw_input()` to `input()` for those of us that will be using Python 2?

```
try:
   input = raw_input
except NameError:
   pass
```

Once you have done that, please also sign our Contributor License Agreement here: https://docs.google.com/a/uber.com/forms/d/1pAwS_-dA1KhPlfxzYLBqK6rsSWwRwH95OCCZrcsY5rk/viewform

**Comment by robbiet480** [comment]
:+1: on this, would be great to have as i'm currently having to hold off pushing some code because I need Python3 support.

Thanks!

**Comment by christinekim** [comment]
Hi @robbiet480 - I'll take a look into this again. I think we can take @denismakogon 's changes, but I'll need to bind `raw_input` to `input` like I've described above so the changes don't adversely affect Python 2 users.

**Comment by merrywhether** [comment]
This PR breaks several aspects of Python 2 compatibility. I've made a more comprehensive PR that preserves Python 2 compatibility while also adding Python 3 compatability.

**Comment by christinekim** [comment]
+1 @merrywhether, who submitted https://github.com/uber/rides-python-sdk/pull/9 to support Python 3 which has been accepted now.

**Pull request closed without merging**
