### PR TITLE
Describe variables used in authorization flow

### PR DESCRIPTION
**Pull request by albertyw**

### CODE REVIEW

**Comment by christinekim** [comment]
Wordsmithing for some extra detail. How about:

> You can find `YOUR_CLIENT_ID` and `YOUR_CLIENT_SECRET` in the [developer dashboard](https://developer.uber.com/dashboard/) under the settings tab of your application.  `YOUR_PERMISSION_SCOPES` is the [list of scopes](https://developer.uber.com/docs/rides/scopes) you have requested in the authorizations tab. Note that `YOUR_REDIRECT_URL` must match the value you provided when you registered your application.

**Comment by christinekim** [comment]
And please sign our cla (t.uber.com/cla) so we can accept your PR when it's ready!

**Comment by albertyw** [comment]
@christinekim updated with your quote.  

I assume I don't have to sign the cla since I work at uber already.

**Comment by christinekim** [comment]
Ah yes. Accepted, thanks!

**Pull request merged**
