### PR TITLE
fix/surge-errors-safe-check

### PR DESCRIPTION
**Pull request by jheld**
My app saw a KeyError on `errors`.

### CODE REVIEW

**Comment by Subzidion** [comment]
What's the `.idea/vcs.xml` file for?

**Comment by jheld** [comment]
@Subzidion that was an accidental PyCharm thing. I've rebased it out.

I have the error check just in case the API decides to return only 1 error. For instance, in `HTTPError` it can include a `error` key in the response. So, just in case.

**Comment by Subzidion** [comment]
Ah, ok. I was getting mixed up with `errors` versus `error.` The variable on line 717 should probably be called `errors` instead since it's a list, just to make it clearer when you're grabbing the first element on line 719. Just my two cents. Looks good to me, though.

**Comment by jheld** [comment]
@Subzidion did as you suggested (agreed), and then made the code a little smaller with a ternary `if`, for getting `error` set.

**Comment by Subzidion** [comment]
Looks good to me. All the tests are still passing on my machine after those changes. :+1:

**Comment by jheld** [comment]
So what is the next step toward this being merged?

**Comment by Subzidion** [comment]
Not sure. I'll tag @dustinwhittle and @christinekim to give them a notification about it.

**Comment by dustinwhittle** [comment]
Thanks for your contributions!

**Pull request merged**
